name: On Release
on:
  release:
    types: [published]


jobs:
  build-python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12 
    
    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Install builder tool
      run : pip install https://github.com/GamuNetwork/devtools/releases/download/1.5.4/build_tool-1.5.4-py3-none-any.whl


    - name: build
      run : cd python && python pack.py -pv ${{ github.event.release.tag_name }} --debug


    - name: Publish
      uses: AButler/upload-release-assets@v3.0
      with:
        files: "python/dist/*"
        repo-token: ${{ secrets.GITHUB_TOKEN }}

  build-javascript:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org

    - name: Install dependencies
      run: cd javascript && npm ci
    
    - name: setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12 
    
    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Install builder tool
      run : pip install https://github.com/GamuNetwork/devtools/releases/download/1.5.7/build_tool-1.5.7-py3-none-any.whl
      
    - name: build
      run : cd javascript && python pack.py -pv ${{ github.event.release.tag_name }} --debug --publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}


