name: On Release
on:
  # release:
  #   types: [published]
  #for testing, do it on push
  push:
    branches:
      - main

jobs:
  build-python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12 
    
    - name: Update pip
      run: python -m pip install --upgrade pip
    
    - name: Install dependencies
      run: pip install -r python/requirements.txt

    - name: Set Package version to tag of release
      run: sed -i "s/{version}/${{ github.event.release.tag_name }}/g" python/pyproject.toml

    - name: Build
      run: python -m build python

    - name: Publish
      uses: AButler/upload-release-assets@v3.0
      with:
        files: "python/dist/*"
        repo-token: ${{ secrets.GITHUB_TOKEN }}

  build-javascript:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: go to javascript directory
      run: cd javascript

    - name: Install dependencies
      run: npm install

    - run: sed -i "s/{version}/${{ github.event.release.tag_name }}/g" javascript/package.json
    - run: sed -i "s/{version}/${{ github.event.release.tag_name }}/g" javascript/package-lock.json

    - name: publish
      run: npm publish