name: On Release
on:
  release:
    types: [published]


jobs:
  build-python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12 
    
    - name: Update pip
      run: python -m pip install --upgrade pip
    
    - name: Install dependencies
      run: pip install -r python/install-requirements.txt

    - name: Set Package version to tag of release
      run: sed -i "s/{version}/${{ github.event.release.tag_name }}/g" python/pyproject.toml

    - name: Build
      run: python -m build python

    - name: Publish
      uses: AButler/upload-release-assets@v3.0
      with:
        files: "python/dist/*"
        repo-token: ${{ secrets.GITHUB_TOKEN }}

  build-javascript:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org

    - name: Install dependencies
      run: cd javascript && npm ci

    - name: build
      run: cd javascript && npm run build

    - run: sed -i "s/{version}/${{ github.event.release.tag_name }}/g" javascript/package.json
    - run: sed -i "s/{version}/${{ github.event.release.tag_name }}/g" javascript/package-lock.json

    - run: cd javascript && npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

