name: On Release
on:
  release:
    types: [published]


jobs:

#region BUILD
  build-python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12 
    
    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Install requirements
      run: pip install -r python/requirements.txt


    - name: build
      run : cd python && python pack.py -pv ${{ github.event.release.tag_name }} --debug

    - name: Store artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: python/dist/*

    - name: Publish release assets
      uses: AButler/upload-release-assets@v3.0
      with:
        files: "python/dist/*"
        repo-token: ${{ secrets.GITHUB_TOKEN }}

  build-javascript:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org

    - name: Install dependencies
      run: cd javascript && npm ci
    
    - name: setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12 
    
    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Install feanor
      run: pip install feanor
    
    - name: Install gamuLogger
    # will be deleted as soon as the package is published to PyPI and gamuLogger is set as a dependency of feanor
      run: pip install https://github.com/GamuNetwork/logger/releases/download/2.0.3/gamu_logger-2.0.3-py3-none-any.whl#sha256=74bd0953ecd02148e988a43f90bc2e393a295340e19443316650ee14f3e9b82b
      
    - name: build
      run : cd javascript && python pack.py -pv ${{ github.event.release.tag_name }} --debug --publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

#endregion

#region PYTHON_PUBLISH
  publish-test-pypi:
    name: Publish to Test PyPI
    needs: build-python
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/gamuLogger
    permissions:
      id-token: write
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  # publish-pypi:
  #   name: Publish to PyPI
  #   needs: build-python
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/p/gamuLogger
  #   permissions:
  #     id-token: write
    
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: python-package-distributions
  #         path: dist/
  #     - name: Publish to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1

#endregion